import { BackupFrequency, BackupType, CompressionLevel, DestinationType, EncryptionType, InternetBehaviour, RetentionMode } from './backup.dto';

export const BACKUP_SETTING_KEY = 'backup.config';
export const PG_BIN_DEFAULT = 'C:\\Program Files\\PostgreSQL\\18\\bin';

export const BACKUP_DEFAULTS = {
  frequency: BackupFrequency.Daily,
  dailyConfig: { times: ['02:00'] },
  weeklyConfig: { days: [0], time: '03:00' },
  customCronExpression: '',
  customIntervalMinutes: 60,
  types: [BackupType.Full],
  includes: {
    database: true,
    schemaOnly: false,
    databaseData: true,
    uploadedImages: true,
    productImages: true,
    customerDocuments: true,
    generatedReports: false,
    attachments: false,
    envFile: true,
    configFiles: true,
    posSettings: true,
    orgSettings: true,
    printerConfig: true,
    receiptTemplates: true,
    kitchenPrinterSettings: true,
    logs: false,
    auditLogs: false,
    scheduledTasks: false,
  },
  destinations: [
    { type: DestinationType.Local, path: 'backup', label: 'Local Backup', enabled: true },
  ],
  retention: {
    mode: RetentionMode.KeepLast,
    keepLastCount: 14,
    keepDays: 30,
    smartDaily: 30,
    smartWeekly: 12,
    smartMonthly: 12,
  },
  compression: CompressionLevel.Normal,
  encryption: { type: EncryptionType.None, password: '' },
  verification: { verifyIntegrity: true, testRestore: false, sha256Checksum: true },
  notifications: {
    on: ['failed'],
    channels: ['desktop'],
    emailAddress: '',
    phoneNumber: '',
  },
  cleanup: { deleteExpired: true, deleteTempFiles: true, removeFailedFiles: true },
  internetBehaviour: InternetBehaviour.LocalOnly,
  namingFormat: 'POS-CAFE_{TYPE}_{DATE}_{TIME}',
  schedule: { time: '02:00', dayOfWeek: 7, timezone: 'UTC', customIntervalMinutes: 60, cronExpression: '' },
  advanced: {
    maxThreads: 1,
    compressionLevel: 6,
    pauseBusinessHours: false,
    businessHoursStart: '08:00',
    businessHoursEnd: '22:00',
    skipIfBusy: false,
    retryCount: 3,
    retryDelayMinutes: 5,
    backupTimeoutMinutes: 60,
    maxDiskUsageGb: 50,
    autoDiskSpaceCheck: true,
  },
};
