package com.poscafe.pos

import com.poscafe.pos.data.repo.CartEngine
import kotlinx.serialization.json.*
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.util.UUID

/**
 * Pricing parity with the server.
 *
 * The device prints a receipt offline; the server re-prices the same cart on
 * sync. If these disagree the customer's receipt is wrong and the books drift.
 * Vectors are generated by `apps/api/scripts/export-cart-vectors.ts` from the
 * REAL server pricing services — regenerate them after any pricing change.
 */
class CartVectorParityTest {

    private val vectors: JsonObject by lazy {
        val stream = javaClass.classLoader!!.getResourceAsStream("cart-vectors.json")
            ?: error("cart-vectors.json missing — run: pnpm --filter @erp/api exec ts-node scripts/export-cart-vectors.ts")
        Json.parseToJsonElement(stream.bufferedReader().readText()).jsonObject
    }

    private fun JsonObject.dbl(key: String): Double? =
        (this[key] as? JsonPrimitive)?.contentOrNull?.toDoubleOrNull()

    private fun toCartLine(spec: JsonObject): CartEngine.CartLine {
        val modifiers = (spec["modifierDeltas"] as? JsonArray)?.mapIndexed { i, d ->
            CartEngine.ModifierSel("m$i", "mod$i", d.jsonPrimitive.double)
        } ?: emptyList()
        val accompaniments = (spec["accompanimentImpacts"] as? JsonArray)?.mapIndexed { i, d ->
            CartEngine.AccompanimentSel("a$i", "acc$i", d.jsonPrimitive.double)
        } ?: emptyList()
        return CartEngine.CartLine(
            lineId = UUID.randomUUID().toString(),
            menuItemId = "item",
            name = spec["name"]!!.jsonPrimitive.content,
            quantity = spec["quantity"]!!.jsonPrimitive.double,
            baseUnitPrice = spec["baseUnitPrice"]!!.jsonPrimitive.double,
            modifiers = modifiers,
            accompaniments = accompaniments,
            discountPercent = spec.dbl("discountPercent") ?: 0.0,
            taxRatePercent = spec.dbl("taxRatePercent") ?: 0.0,
            taxInclusive = (spec["taxInclusive"] as? JsonPrimitive)?.contentOrNull?.toBoolean() ?: false,
        )
    }

    @Test
    fun `every server vector reproduces on device`() {
        val cases = vectors["vectors"]!!.jsonArray
        assertTrue("no vectors loaded", cases.isNotEmpty())

        val failures = mutableListOf<String>()
        for (case in cases.map { it.jsonObject }) {
            val id = case["id"]!!.jsonPrimitive.content
            val txPct = case.dbl("transactionDiscountPercent") ?: 0.0
            val lines = case["lines"]!!.jsonArray.map { toCartLine(it.jsonObject) }
            val expected = case["expected"]!!.jsonObject

            val actual = CartEngine.totals(lines, txPct)

            // 1 minor unit of tolerance: the server keeps 6dp Decimals, the
            // device rounds to 2dp for display/printing.
            fun check(field: String, exp: Double, act: Double) {
                if (kotlin.math.abs(exp - act) > 0.01) {
                    failures += "$id.$field: server=$exp device=$act"
                }
            }
            check("total", expected.dbl("total")!!, actual.total)
            check("taxTotal", expected.dbl("taxTotal")!!, actual.taxTotal)
            check("subtotal", expected.dbl("subtotal")!!, actual.subtotal)
            check("discountTotal", expected.dbl("discountTotal")!!, actual.discountTotal)
        }

        assertEquals("pricing drift vs server:\n" + failures.joinToString("\n"), 0, failures.size)
    }
}
