-- =====================================================================
-- BRIDGE 10 - additive DDL (legacy schema -> squashed baseline)
-- Generated by: prisma migrate diff --from-url <legacy clone> --to-url ref_baseline_20260727 --script
-- Source draft: reviewed line by line on 2026-09-17; committed as the permanent record.
-- ---------------------------------------------------------------------
-- Additive only. The legacy application keeps working against this state,
-- which is what makes a pre-contract rollback a configuration change.
-- The two DROP INDEX statements are index replacements, not data loss.
-- =====================================================================
-- CreateEnum
CREATE TYPE "public"."AccountClassification" AS ENUM ('asset', 'liability', 'equity', 'revenue', 'expense', 'off_balance');

-- CreateEnum
CREATE TYPE "public"."AcquisitionMethod" AS ENUM ('purchased', 'donated', 'leased', 'constructed', 'transferred_in', 'gifted');

-- CreateEnum
CREATE TYPE "public"."AssetStatus" AS ENUM ('active', 'under_maintenance', 'disposed', 'lost_stolen', 'in_repair', 'reserved');

-- CreateEnum
CREATE TYPE "public"."AssignmentEntityType" AS ENUM ('employee', 'teacher', 'student', 'department', 'branch', 'room', 'vehicle', 'clinic', 'store');

-- CreateEnum
CREATE TYPE "public"."CashFlowClass" AS ENUM ('operating', 'investing', 'financing', 'none');

-- CreateEnum
CREATE TYPE "public"."ControlAccountType" AS ENUM ('ar', 'ap', 'inventory', 'fixed_assets', 'payroll', 'tax');

-- CreateEnum
CREATE TYPE "public"."DepreciationMethod" AS ENUM ('straight_line', 'declining_balance', 'double_declining', 'units_of_production', 'manual');

-- CreateEnum
CREATE TYPE "public"."DisposalMethod" AS ENUM ('sold', 'scrapped', 'donated', 'lost', 'stolen', 'destroyed');

-- CreateEnum
CREATE TYPE "public"."InventoryMovementType" AS ENUM ('STOCK_IN', 'STOCK_OUT', 'STOCK_TRANSFER_OUT', 'STOCK_TRANSFER_IN', 'ADJUSTMENT_GAIN', 'ADJUSTMENT_LOSS', 'WASTE', 'EXPIRY_WRITE_OFF', 'RETURN_RESTOCK', 'RETURN_TO_SUPPLIER', 'INTERNAL_CONSUMPTION', 'PROMO_SAMPLE', 'PRODUCTION_CONSUME', 'PRODUCTION_OUTPUT', 'REVALUATION');

-- CreateEnum
CREATE TYPE "public"."MaintenanceType" AS ENUM ('preventive', 'corrective', 'emergency', 'scheduled', 'calibration');

-- CreateEnum
CREATE TYPE "public"."MeasurementMethod" AS ENUM ('count', 'manual_volume', 'digital_weight');

-- CreateEnum
CREATE TYPE "public"."NormalBalance" AS ENUM ('debit', 'credit');

-- CreateEnum
CREATE TYPE "public"."PickingStrategy" AS ENUM ('FEFO', 'FIFO', 'MANUAL', 'SERIAL');

-- CreateEnum
CREATE TYPE "public"."RecurrenceType" AS ENUM ('HOURLY', 'EVERY_X_HOURS', 'DAILY', 'WEEKDAYS', 'WEEKENDS', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', 'CUSTOM_DATES', 'SPECIFIC_SHIFT', 'AFTER_COMPLETION');

-- CreateEnum
CREATE TYPE "public"."ReportSection" AS ENUM ('current_assets', 'non_current_assets', 'current_liabilities', 'long_term_liabilities', 'equity', 'revenue', 'contra_revenue', 'cogs', 'operating_expense', 'other_income', 'other_expense', 'off_balance');

-- CreateEnum
CREATE TYPE "public"."SerialStatus" AS ENUM ('in_stock', 'issued', 'returned', 'scrapped');

-- CreateEnum
CREATE TYPE "public"."StockReservationStatus" AS ENUM ('active', 'released', 'consumed');

-- CreateEnum
CREATE TYPE "public"."TaskArea" AS ENUM ('KITCHEN', 'COFFEE_STATION', 'BAR', 'DINING_AREA', 'RETAIL_FLOOR', 'WAREHOUSE', 'OFFICE', 'CASHIER', 'STORAGE', 'DELIVERY', 'RESTROOM', 'PARKING', 'OTHER');

-- CreateEnum
CREATE TYPE "public"."TaskCategory" AS ENUM ('OPENING', 'CLOSING', 'CLEANING', 'KITCHEN', 'COFFEE_BAR', 'DINING_AREA', 'RETAIL_FLOOR', 'WAREHOUSE', 'INVENTORY', 'PURCHASING', 'ACCOUNTING', 'CASH_MANAGEMENT', 'SECURITY', 'MAINTENANCE', 'EQUIPMENT', 'MARKETING', 'COMPLIANCE', 'AUDIT', 'CUSTOMER_SERVICE', 'CUSTOM');

-- CreateEnum
CREATE TYPE "public"."TaskMgmtStatus" AS ENUM ('DRAFT', 'PENDING', 'ASSIGNED', 'IN_PROGRESS', 'WAITING', 'REVIEW', 'VERIFIED', 'COMPLETED', 'CANCELLED', 'SKIPPED', 'OVERDUE');

-- CreateEnum
CREATE TYPE "public"."TaskNotificationChannel" AS ENUM ('IN_APP', 'PUSH', 'SMS', 'EMAIL', 'WHATSAPP', 'TELEGRAM');

-- CreateEnum
CREATE TYPE "public"."TaskPriority" AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'OPTIONAL');

-- CreateEnum
CREATE TYPE "public"."TaskType" AS ENUM ('ONE_TIME', 'RECURRING', 'SHIFT', 'OPENING', 'CLOSING', 'CLEANING', 'MAINTENANCE', 'INVENTORY', 'AUDIT', 'PURCHASE', 'INCIDENT', 'COMPLIANCE', 'FOOD_SAFETY', 'EQUIPMENT_INSPECTION', 'CUSTOM');

-- CreateEnum
CREATE TYPE "public"."VerificationMethod" AS ENUM ('MANAGER_PIN', 'PASSWORD', 'BIOMETRIC', 'DIGITAL_SIGNATURE', 'PHOTO_PROOF');

-- DropIndex
DROP INDEX "public"."Setting_organizationId_scope_key_key";

-- AlterTable (additive half: the accountType/isGroup drops move to bridge-30)
ALTER TABLE "public"."Account" ADD COLUMN     "allowBudgeting" BOOLEAN,
ADD COLUMN     "allowManualPosting" BOOLEAN,
ADD COLUMN     "allowReconciliation" BOOLEAN,
ADD COLUMN     "categoryId" TEXT,
ADD COLUMN     "controlAccountType" "public"."ControlAccountType",
ADD COLUMN     "deprecatedAt" TIMESTAMP(3),
ADD COLUMN     "isPostable" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "normalBalance" "public"."NormalBalance" NOT NULL DEFAULT 'debit',
ADD COLUMN     "reportSection" "public"."ReportSection",
ADD COLUMN     "sortOrder" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "public"."CashSession" ADD COLUMN     "deviceId" TEXT;

-- AlterTable
ALTER TABLE "public"."InventoryBatch" ADD COLUMN     "mfgDate" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "public"."InventoryCountLine" ADD COLUMN     "parentProductId" TEXT,
ADD COLUMN     "parentProductName" TEXT;

-- AlterTable
ALTER TABLE "public"."InventoryCountSession" ADD COLUMN     "name" TEXT;

-- AlterTable
ALTER TABLE "public"."InventoryLedger" ADD COLUMN     "serialId" TEXT;

-- AlterTable
ALTER TABLE "public"."Invoice" ADD COLUMN     "deviceId" TEXT,
ADD COLUMN     "provisionalNumber" TEXT;

-- AlterTable
ALTER TABLE "public"."JournalEntry" ADD COLUMN     "dimensions" JSONB,
ADD COLUMN     "postingKey" TEXT,
ADD COLUMN     "postingType" TEXT NOT NULL DEFAULT 'primary';

-- AlterTable
ALTER TABLE "public"."JournalLine" ADD COLUMN     "dimensions" JSONB;

-- AlterTable
ALTER TABLE "public"."MenuProduct" ADD COLUMN     "uomId" TEXT;

-- AlterTable
ALTER TABLE "public"."Order" ADD COLUMN     "deviceId" TEXT,
ADD COLUMN     "provisionalNumber" TEXT;

-- AlterTable
ALTER TABLE "public"."Partner" ADD COLUMN     "creditHold" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "creditLimit" DECIMAL(20,2) NOT NULL DEFAULT 0,
ADD COLUMN     "discountPercentOverride" DECIMAL(9,4) NOT NULL DEFAULT 0,
ADD COLUMN     "paymentTermId" TEXT;

-- AlterTable
ALTER TABLE "public"."PartnerCategory" ADD COLUMN     "discountPercentOverride" DECIMAL(9,4) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "public"."Product" ADD COLUMN     "actualEmptyWeightG" DECIMAL(20,6),
ADD COLUMN     "allowFractionalSale" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "allowPartialBottle" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "cogsAccountOverrideId" TEXT,
ADD COLUMN     "containerVolumeMl" DECIMAL(20,6),
ADD COLUMN     "conversionFactorMlPerG" DECIMAL(20,10),
ADD COLUMN     "damageAccountOverrideId" TEXT,
ADD COLUMN     "emptyBottleWeightG" DECIMAL(20,6),
ADD COLUMN     "expenseAccountOverrideId" TEXT,
ADD COLUMN     "expiryAccountOverrideId" TEXT,
ADD COLUMN     "expiryTracking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "fullBottleWeightG" DECIMAL(20,6),
ADD COLUMN     "image" TEXT,
ADD COLUMN     "incomeAccountOverrideId" TEXT,
ADD COLUMN     "inventoryAccountOverrideId" TEXT,
ADD COLUMN     "liquidWeightG" DECIMAL(20,6),
ADD COLUMN     "maxQuantity" DECIMAL(20,6) NOT NULL DEFAULT 0,
ADD COLUMN     "maxSaleQty" DECIMAL(20,6),
ADD COLUMN     "measurementMethod" "public"."MeasurementMethod" NOT NULL DEFAULT 'count',
ADD COLUMN     "minSaleQty" DECIMAL(20,6),
ADD COLUMN     "pickingStrategy" "public"."PickingStrategy" NOT NULL DEFAULT 'FEFO',
ADD COLUMN     "productionUomId" TEXT,
ADD COLUMN     "recipeUomId" TEXT,
ADD COLUMN     "salesUomId" TEXT,
ADD COLUMN     "serialTracking" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "shrinkageAccountOverrideId" TEXT,
ADD COLUMN     "standardPourMl" DECIMAL(20,6),
ADD COLUMN     "varianceGainAccountOverrideId" TEXT,
ADD COLUMN     "varianceToleranceG" DECIMAL(20,6);

-- AlterTable
ALTER TABLE "public"."ProductCategory" ADD COLUMN     "cogsAccountId" TEXT,
ADD COLUMN     "damageAccountId" TEXT,
ADD COLUMN     "expiryAccountId" TEXT,
ADD COLUMN     "internalUseAccountId" TEXT,
ADD COLUMN     "inventoryAccountId" TEXT,
ADD COLUMN     "promoExpenseAccountId" TEXT,
ADD COLUMN     "shrinkageAccountId" TEXT,
ADD COLUMN     "varianceGainAccountId" TEXT;

-- AlterTable
ALTER TABLE "public"."Receipt" ADD COLUMN     "deviceId" TEXT,
ADD COLUMN     "provisionalNumber" TEXT;

-- AlterTable
ALTER TABLE "public"."ReportBalanceSheetSnapshot" ADD COLUMN     "accountCategoryKey" TEXT,
ADD COLUMN     "classification" TEXT,
ADD COLUMN     "normalBalance" TEXT,
ADD COLUMN     "reportSection" TEXT,
ADD COLUMN     "schemaVersion" INTEGER NOT NULL DEFAULT 2;

-- AlterTable
ALTER TABLE "public"."ReportTrialBalanceSnapshot" ADD COLUMN     "accountCategoryKey" TEXT,
ADD COLUMN     "classification" TEXT,
ADD COLUMN     "normalBalance" TEXT,
ADD COLUMN     "schemaVersion" INTEGER NOT NULL DEFAULT 2;

-- AlterTable
ALTER TABLE "public"."Setting" ADD COLUMN     "scopeId" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "scopeType" TEXT NOT NULL DEFAULT 'organization';

-- AlterTable
ALTER TABLE "public"."Tax" ADD COLUMN     "vatCategory" TEXT NOT NULL DEFAULT 'standard';

-- AlterTable
ALTER TABLE "public"."UnitOfMeasure" ADD COLUMN     "categoryId" TEXT,
ADD COLUMN     "factor" DECIMAL(18,6) NOT NULL DEFAULT 1,
ADD COLUMN     "roundingPrecision" DECIMAL(18,6) NOT NULL DEFAULT 0.000001,
ADD COLUMN     "symbol" TEXT,
ADD COLUMN     "uomType" TEXT NOT NULL DEFAULT 'reference';

-- CreateTable
CREATE TABLE "public"."AccountCategory" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "classification" "public"."AccountClassification" NOT NULL,
    "normalBalance" "public"."NormalBalance" NOT NULL,
    "reportSection" "public"."ReportSection" NOT NULL,
    "cashFlowClass" "public"."CashFlowClass" NOT NULL DEFAULT 'operating',
    "isContra" BOOLEAN NOT NULL DEFAULT false,
    "isCashEquivalent" BOOLEAN NOT NULL DEFAULT false,
    "allowReconciliation" BOOLEAN NOT NULL DEFAULT false,
    "allowManualPosting" BOOLEAN NOT NULL DEFAULT true,
    "allowBudgeting" BOOLEAN NOT NULL DEFAULT false,
    "isSystem" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "systemVersion" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AccountCategory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Asset" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetCode" TEXT NOT NULL,
    "barcode" TEXT,
    "qrCode" TEXT,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "serialNumber" TEXT,
    "brand" TEXT,
    "model" TEXT,
    "manufacturer" TEXT,
    "categoryId" TEXT,
    "department" TEXT,
    "branchId" TEXT,
    "location" TEXT,
    "assignedToId" TEXT,
    "assignedToType" "public"."AssignmentEntityType",
    "assignmentDate" TIMESTAMP(3),
    "purchaseDate" TIMESTAMP(3),
    "supplierId" TEXT,
    "invoiceNumber" TEXT,
    "purchaseCost" DECIMAL(18,6),
    "currentValue" DECIMAL(18,6),
    "salvageValue" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "usefulLife" INTEGER NOT NULL DEFAULT 60,
    "usefulLifeUnit" TEXT NOT NULL DEFAULT 'months',
    "acquisitionMethod" "public"."AcquisitionMethod" NOT NULL DEFAULT 'purchased',
    "capitalizedCost" DECIMAL(18,6),
    "image" TEXT,
    "notes" TEXT,
    "customFields" JSONB NOT NULL DEFAULT '{}',
    "status" "public"."AssetStatus" NOT NULL DEFAULT 'active',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "Asset_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetAcquisition" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "vendor" TEXT,
    "vendorId" TEXT,
    "purchaseOrderId" TEXT,
    "invoiceId" TEXT,
    "taxes" DECIMAL(18,6),
    "freight" DECIMAL(18,6),
    "installationCost" DECIMAL(18,6),
    "otherCosts" DECIMAL(18,6),
    "capitalizedCost" DECIMAL(18,6),
    "acquisitionDate" TIMESTAMP(3),
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,

    CONSTRAINT "AssetAcquisition_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetAssignment" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "assignedToId" TEXT,
    "assignedToType" "public"."AssignmentEntityType",
    "assignedToName" TEXT,
    "assignedDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "returnedDate" TIMESTAMP(3),
    "conditionBefore" TEXT,
    "conditionAfter" TEXT,
    "responsiblePerson" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetAssignment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetCategory" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "parentId" TEXT,
    "depreciationMethod" "public"."DepreciationMethod" NOT NULL DEFAULT 'straight_line',
    "defaultUsefulLife" INTEGER NOT NULL DEFAULT 60,
    "defaultResidualValue" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "AssetCategory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetCheckInOut" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "checkedOutTo" TEXT,
    "checkedOutToType" TEXT,
    "checkoutDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expectedReturnDate" TIMESTAMP(3),
    "returnDate" TIMESTAMP(3),
    "conditionBefore" TEXT,
    "conditionAfter" TEXT,
    "checkedOutById" TEXT,
    "checkedInById" TEXT,
    "status" TEXT NOT NULL DEFAULT 'checked_out',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetCheckInOut_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetDepreciation" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "period" TEXT NOT NULL,
    "method" "public"."DepreciationMethod" NOT NULL DEFAULT 'straight_line',
    "assetCost" DECIMAL(18,6) NOT NULL,
    "salvageValue" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "usefulLife" INTEGER NOT NULL,
    "depreciationAmount" DECIMAL(18,6) NOT NULL,
    "accumulatedDepr" DECIMAL(18,6) NOT NULL,
    "bookValue" DECIMAL(18,6) NOT NULL,
    "isPosted" BOOLEAN NOT NULL DEFAULT false,
    "journalEntryId" TEXT,
    "postedAt" TIMESTAMP(3),
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetDepreciation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetDisposal" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "disposalMethod" "public"."DisposalMethod" NOT NULL,
    "disposalDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "disposalValue" DECIMAL(18,6),
    "bookValueAtDisposal" DECIMAL(18,6),
    "gainLoss" DECIMAL(18,6),
    "approvedBy" TEXT,
    "reason" TEXT,
    "notes" TEXT,
    "documents" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetDisposal_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetDocument" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "documentType" TEXT,
    "fileName" TEXT,
    "fileId" TEXT,
    "fileUrl" TEXT,
    "description" TEXT,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "uploadedBy" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AssetDocument_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetInspection" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "inspector" TEXT,
    "inspectionDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "condition" TEXT,
    "isWorking" BOOLEAN NOT NULL DEFAULT true,
    "isDamaged" BOOLEAN NOT NULL DEFAULT false,
    "isMissing" BOOLEAN NOT NULL DEFAULT false,
    "requiresRepair" BOOLEAN NOT NULL DEFAULT false,
    "photos" JSONB NOT NULL DEFAULT '[]',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetInspection_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetInsurance" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "policyNumber" TEXT,
    "company" TEXT,
    "premium" DECIMAL(18,6),
    "coverageAmount" DECIMAL(18,6),
    "startDate" TIMESTAMP(3),
    "renewalDate" TIMESTAMP(3),
    "contactPerson" TEXT,
    "contactPhone" TEXT,
    "notes" TEXT,
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetInsurance_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetMaintenance" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "maintenanceType" "public"."MaintenanceType" NOT NULL DEFAULT 'preventive',
    "title" TEXT NOT NULL,
    "description" TEXT,
    "technician" TEXT,
    "vendor" TEXT,
    "scheduledDate" TIMESTAMP(3),
    "completedDate" TIMESTAMP(3),
    "cost" DECIMAL(18,6),
    "nextMaintenanceDate" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'scheduled',
    "notes" TEXT,
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetMaintenance_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetRepair" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "breakdownDate" TIMESTAMP(3) NOT NULL,
    "repairDate" TIMESTAMP(3),
    "description" TEXT,
    "vendor" TEXT,
    "sparePartsCost" DECIMAL(18,6),
    "laborCost" DECIMAL(18,6),
    "totalCost" DECIMAL(18,6),
    "downtimeHours" DECIMAL(10,2),
    "vendorInvoiceRef" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "notes" TEXT,
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetRepair_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetRevaluation" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "previousValue" DECIMAL(18,6) NOT NULL,
    "newValue" DECIMAL(18,6) NOT NULL,
    "revaluationDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reason" TEXT,
    "approvedBy" TEXT,
    "notes" TEXT,
    "documents" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetRevaluation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetTransfer" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "fromLocation" TEXT,
    "toLocation" TEXT,
    "fromBranchId" TEXT,
    "toBranchId" TEXT,
    "fromDepartment" TEXT,
    "toDepartment" TEXT,
    "fromPersonId" TEXT,
    "toPersonId" TEXT,
    "reason" TEXT,
    "approvedBy" TEXT,
    "transferDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetTransfer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."AssetWarranty" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "warrantyStart" TIMESTAMP(3) NOT NULL,
    "warrantyEnd" TIMESTAMP(3) NOT NULL,
    "vendor" TEXT,
    "contactPerson" TEXT,
    "contactPhone" TEXT,
    "contactEmail" TEXT,
    "terms" TEXT,
    "coverage" TEXT,
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "notified90d" BOOLEAN NOT NULL DEFAULT false,
    "notified30d" BOOLEAN NOT NULL DEFAULT false,
    "notifiedExpired" BOOLEAN NOT NULL DEFAULT false,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,

    CONSTRAINT "AssetWarranty_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."BottleCountLine" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "productName" TEXT NOT NULL,
    "unit" TEXT,
    "systemMl" DECIMAL(20,6) NOT NULL,
    "sealedFullCount" DECIMAL(20,6) NOT NULL DEFAULT 0,
    "countedMl" DECIMAL(20,6),
    "varianceMl" DECIMAL(20,6) NOT NULL DEFAULT 0,
    "varianceG" DECIMAL(20,6) NOT NULL DEFAULT 0,
    "expectedShots" DECIMAL(20,6),
    "soldShots" DECIMAL(20,6),
    "reason" TEXT,
    "confidence" TEXT NOT NULL DEFAULT 'GOOD',
    "countedById" TEXT,
    "countedAt" TIMESTAMP(3),

    CONSTRAINT "BottleCountLine_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."BottleCountReading" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "lineId" TEXT NOT NULL,
    "bottleNumber" TEXT,
    "measuredWeightG" DECIMAL(20,6) NOT NULL,
    "expectedWeightG" DECIMAL(20,6),
    "remainingMl" DECIMAL(20,6) NOT NULL,
    "confidence" TEXT NOT NULL DEFAULT 'GOOD',

    CONSTRAINT "BottleCountReading_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."BottleCountSession" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "countCode" TEXT NOT NULL,
    "name" TEXT,
    "locationId" TEXT NOT NULL,
    "countType" TEXT NOT NULL DEFAULT 'closing',
    "status" TEXT NOT NULL DEFAULT 'draft',
    "notes" TEXT,
    "startedById" TEXT,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "submittedById" TEXT,
    "submittedAt" TIMESTAMP(3),
    "approvedById" TEXT,
    "approvedAt" TIMESTAMP(3),
    "adjustmentId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "BottleCountSession_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."BottleMeasurement" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "bottleNumber" TEXT,
    "locationId" TEXT NOT NULL,
    "sessionId" TEXT,
    "openingWeightG" DECIMAL(20,6),
    "expectedWeightG" DECIMAL(20,6),
    "measuredWeightG" DECIMAL(20,6) NOT NULL,
    "remainingMl" DECIMAL(20,6) NOT NULL,
    "varianceMl" DECIMAL(20,6) NOT NULL DEFAULT 0,
    "varianceG" DECIMAL(20,6) NOT NULL DEFAULT 0,
    "measurementSource" TEXT NOT NULL DEFAULT 'MANUAL',
    "confidence" TEXT NOT NULL DEFAULT 'GOOD',
    "measuredById" TEXT,
    "measuredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "remarks" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BottleMeasurement_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."CostCenter" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'cost',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "CostCenter_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."InventoryException" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "invoiceId" TEXT,
    "invoiceNumber" TEXT,
    "locationId" TEXT,
    "productId" TEXT,
    "menuItemId" TEXT,
    "description" TEXT,
    "quantity" DECIMAL(20,6) NOT NULL DEFAULT 0,
    "kind" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "stackTrace" TEXT,
    "payload" JSONB,
    "status" TEXT NOT NULL DEFAULT 'open',
    "assignedToId" TEXT,
    "resolvedById" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "resolutionNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "InventoryException_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."InventoryPostingRule" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "movementType" "public"."InventoryMovementType" NOT NULL,
    "lineIndex" INTEGER NOT NULL DEFAULT 0,
    "debitOrCredit" TEXT NOT NULL,
    "accountSource" TEXT NOT NULL DEFAULT 'account_mapping',
    "accountMappingKey" TEXT,
    "literalAccountId" TEXT,
    "productId" TEXT,
    "categoryId" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,

    CONSTRAINT "InventoryPostingRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."InventorySerial" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "variantId" TEXT,
    "locationId" TEXT NOT NULL,
    "serialNumber" TEXT NOT NULL,
    "batchId" TEXT,
    "unitCost" DECIMAL(20,6),
    "status" "public"."SerialStatus" NOT NULL DEFAULT 'in_stock',
    "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "issuedAt" TIMESTAMP(3),
    "receiptRef" TEXT,
    "issueRef" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "InventorySerial_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."MembershipTier" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "discountPercent" DECIMAL(9,4) NOT NULL DEFAULT 0,
    "minLifetimeSpend" DECIMAL(20,6) NOT NULL DEFAULT 0,
    "color" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MembershipTier_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."PaymentTerm" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "netDays" INTEGER NOT NULL DEFAULT 0,
    "discountDays" INTEGER,
    "discountPercent" DECIMAL(9,4),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "PaymentTerm_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."PosDevice" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "branchId" TEXT,
    "name" TEXT NOT NULL,
    "platform" TEXT NOT NULL DEFAULT 'android',
    "tokenHash" TEXT NOT NULL,
    "prefix" TEXT NOT NULL,
    "registeredById" TEXT,
    "lastSeenAt" TIMESTAMP(3),
    "lastPushSeq" INTEGER NOT NULL DEFAULT 0,
    "revokedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PosDevice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ProductPackaging" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "quantity" DECIMAL(20,6) NOT NULL DEFAULT 1,
    "barcode" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProductPackaging_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."ProductUomConversion" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "fromUomId" TEXT NOT NULL,
    "toUomId" TEXT NOT NULL,
    "factor" DECIMAL(20,10) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProductUomConversion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."StockPostingJob" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "invoiceId" TEXT NOT NULL,
    "invoiceNumber" TEXT NOT NULL,
    "orderId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 5,
    "lastError" TEXT,
    "claimToken" TEXT,
    "claimedAt" TIMESTAMP(3),
    "nextRetryAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMP(3),

    CONSTRAINT "StockPostingJob_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."StockReservation" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "variantId" TEXT,
    "variantKey" TEXT NOT NULL DEFAULT '',
    "locationId" TEXT NOT NULL,
    "quantity" DECIMAL(20,6) NOT NULL,
    "status" "public"."StockReservationStatus" NOT NULL DEFAULT 'active',
    "sourceType" TEXT NOT NULL,
    "sourceId" TEXT NOT NULL,
    "reason" TEXT,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "releasedAt" TIMESTAMP(3),
    "consumedAt" TIMESTAMP(3),

    CONSTRAINT "StockReservation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."SyncOpDeadLetter" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "deviceId" TEXT NOT NULL,
    "opId" TEXT NOT NULL,
    "deviceSeq" INTEGER NOT NULL,
    "opType" TEXT NOT NULL,
    "actorUserId" TEXT,
    "occurredAt" TIMESTAMP(3),
    "payload" JSONB NOT NULL,
    "error" TEXT NOT NULL,
    "httpStatus" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'open',
    "resolvedById" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "resolutionNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SyncOpDeadLetter_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."Task" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "branchId" TEXT,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "taskType" "public"."TaskType" NOT NULL DEFAULT 'ONE_TIME',
    "priority" "public"."TaskPriority" NOT NULL DEFAULT 'MEDIUM',
    "status" "public"."TaskMgmtStatus" NOT NULL DEFAULT 'PENDING',
    "category" "public"."TaskCategory",
    "area" "public"."TaskArea",
    "departmentId" TEXT,
    "assignedToId" TEXT,
    "assignedRole" TEXT,
    "supervisorId" TEXT,
    "dueDate" TIMESTAMP(3),
    "dueTime" TEXT,
    "startTime" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "estimatedMinutes" INTEGER,
    "actualMinutes" INTEGER,
    "isRecurring" BOOLEAN NOT NULL DEFAULT false,
    "recurrenceType" "public"."RecurrenceType",
    "recurrenceConfig" JSONB,
    "parentTaskId" TEXT,
    "recurrenceOrder" INTEGER,
    "requiresVerification" BOOLEAN NOT NULL DEFAULT false,
    "verificationMethod" "public"."VerificationMethod",
    "verifiedById" TEXT,
    "verifiedAt" TIMESTAMP(3),
    "verificationPhoto" TEXT,
    "verificationNote" TEXT,
    "checklistProgress" INTEGER NOT NULL DEFAULT 0,
    "checklistTotal" INTEGER NOT NULL DEFAULT 0,
    "photoUrls" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "attachmentUrls" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "generatedByEvent" TEXT,
    "sourceReferenceId" TEXT,
    "sourceReferenceType" TEXT,
    "shiftId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."TaskActivityLog" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "field" TEXT,
    "oldValue" TEXT,
    "newValue" TEXT,
    "description" TEXT,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TaskActivityLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."TaskAutoRule" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "triggerEvent" TEXT NOT NULL,
    "triggerConfig" JSONB,
    "taskTitle" TEXT NOT NULL,
    "taskDescription" TEXT,
    "taskType" "public"."TaskType" NOT NULL,
    "taskCategory" "public"."TaskCategory",
    "taskArea" "public"."TaskArea",
    "taskPriority" "public"."TaskPriority" NOT NULL DEFAULT 'MEDIUM',
    "assignToRole" TEXT,
    "assignToUserId" TEXT,
    "branchId" TEXT,
    "requiresVerification" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,

    CONSTRAINT "TaskAutoRule_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."TaskChecklistItem" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "isCompleted" BOOLEAN NOT NULL DEFAULT false,
    "completedAt" TIMESTAMP(3),
    "completedBy" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TaskChecklistItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."TaskComment" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "parentId" TEXT,
    "content" TEXT NOT NULL,
    "mentions" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "attachmentUrls" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "emojiReactions" JSONB,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "TaskComment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."TaskLabel" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "color" TEXT NOT NULL DEFAULT '#6366f1',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TaskLabel_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."TaskRecurringTemplate" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "taskType" "public"."TaskType" NOT NULL DEFAULT 'RECURRING',
    "taskCategory" "public"."TaskCategory",
    "taskArea" "public"."TaskArea",
    "priority" "public"."TaskPriority" NOT NULL DEFAULT 'MEDIUM',
    "recurrenceType" "public"."RecurrenceType" NOT NULL DEFAULT 'DAILY',
    "recurrenceConfig" JSONB,
    "estimatedMinutes" INTEGER,
    "requiresVerification" BOOLEAN NOT NULL DEFAULT false,
    "verificationMethod" "public"."VerificationMethod",
    "branchId" TEXT,
    "departmentId" TEXT,
    "assignToRole" TEXT,
    "assignToUserId" TEXT,
    "supervisorId" TEXT,
    "checklistTemplate" JSONB,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "TaskRecurringTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."UomCategory" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "referenceUomId" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "createdBy" TEXT,
    "updatedBy" TEXT,
    "deletedAt" TIMESTAMP(3),

    CONSTRAINT "UomCategory_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."_TaskLabelLink" (
    "A" TEXT NOT NULL,
    "B" TEXT NOT NULL,

    CONSTRAINT "_TaskLabelLink_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateIndex
CREATE INDEX "AccountCategory_classification_idx" ON "public"."AccountCategory"("classification" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "AccountCategory_key_key" ON "public"."AccountCategory"("key" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "Asset_organizationId_assetCode_key" ON "public"."Asset"("organizationId" ASC, "assetCode" ASC);

-- CreateIndex
CREATE INDEX "Asset_organizationId_barcode_idx" ON "public"."Asset"("organizationId" ASC, "barcode" ASC);

-- CreateIndex
CREATE INDEX "Asset_organizationId_categoryId_idx" ON "public"."Asset"("organizationId" ASC, "categoryId" ASC);

-- CreateIndex
CREATE INDEX "Asset_organizationId_idx" ON "public"."Asset"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "Asset_organizationId_serialNumber_idx" ON "public"."Asset"("organizationId" ASC, "serialNumber" ASC);

-- CreateIndex
CREATE INDEX "Asset_organizationId_status_idx" ON "public"."Asset"("organizationId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "AssetAcquisition_assetId_idx" ON "public"."AssetAcquisition"("assetId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "AssetAcquisition_assetId_key" ON "public"."AssetAcquisition"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetAcquisition_organizationId_idx" ON "public"."AssetAcquisition"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetAssignment_assetId_idx" ON "public"."AssetAssignment"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetAssignment_assignedToId_idx" ON "public"."AssetAssignment"("assignedToId" ASC);

-- CreateIndex
CREATE INDEX "AssetAssignment_organizationId_idx" ON "public"."AssetAssignment"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetCategory_organizationId_idx" ON "public"."AssetCategory"("organizationId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "AssetCategory_organizationId_name_key" ON "public"."AssetCategory"("organizationId" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "AssetCheckInOut_assetId_idx" ON "public"."AssetCheckInOut"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetCheckInOut_assetId_status_idx" ON "public"."AssetCheckInOut"("assetId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "AssetCheckInOut_organizationId_idx" ON "public"."AssetCheckInOut"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetDepreciation_assetId_idx" ON "public"."AssetDepreciation"("assetId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "AssetDepreciation_organizationId_assetId_period_key" ON "public"."AssetDepreciation"("organizationId" ASC, "assetId" ASC, "period" ASC);

-- CreateIndex
CREATE INDEX "AssetDepreciation_organizationId_idx" ON "public"."AssetDepreciation"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetDepreciation_organizationId_period_idx" ON "public"."AssetDepreciation"("organizationId" ASC, "period" ASC);

-- CreateIndex
CREATE INDEX "AssetDisposal_assetId_idx" ON "public"."AssetDisposal"("assetId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "AssetDisposal_assetId_key" ON "public"."AssetDisposal"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetDisposal_organizationId_idx" ON "public"."AssetDisposal"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetDocument_assetId_idx" ON "public"."AssetDocument"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetDocument_organizationId_idx" ON "public"."AssetDocument"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetInspection_assetId_idx" ON "public"."AssetInspection"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetInspection_organizationId_idx" ON "public"."AssetInspection"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetInsurance_assetId_idx" ON "public"."AssetInsurance"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetInsurance_organizationId_idx" ON "public"."AssetInsurance"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetInsurance_organizationId_renewalDate_idx" ON "public"."AssetInsurance"("organizationId" ASC, "renewalDate" ASC);

-- CreateIndex
CREATE INDEX "AssetMaintenance_assetId_idx" ON "public"."AssetMaintenance"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetMaintenance_assetId_status_idx" ON "public"."AssetMaintenance"("assetId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "AssetMaintenance_organizationId_idx" ON "public"."AssetMaintenance"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetRepair_assetId_idx" ON "public"."AssetRepair"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetRepair_organizationId_idx" ON "public"."AssetRepair"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetRevaluation_assetId_idx" ON "public"."AssetRevaluation"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetRevaluation_organizationId_idx" ON "public"."AssetRevaluation"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetTransfer_assetId_idx" ON "public"."AssetTransfer"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetTransfer_organizationId_idx" ON "public"."AssetTransfer"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetWarranty_assetId_idx" ON "public"."AssetWarranty"("assetId" ASC);

-- CreateIndex
CREATE INDEX "AssetWarranty_organizationId_idx" ON "public"."AssetWarranty"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "AssetWarranty_organizationId_warrantyEnd_idx" ON "public"."AssetWarranty"("organizationId" ASC, "warrantyEnd" ASC);

-- CreateIndex
CREATE INDEX "BottleCountLine_organizationId_sessionId_idx" ON "public"."BottleCountLine"("organizationId" ASC, "sessionId" ASC);

-- CreateIndex
CREATE INDEX "BottleCountLine_sessionId_idx" ON "public"."BottleCountLine"("sessionId" ASC);

-- CreateIndex
CREATE INDEX "BottleCountReading_lineId_idx" ON "public"."BottleCountReading"("lineId" ASC);

-- CreateIndex
CREATE INDEX "BottleCountReading_organizationId_lineId_idx" ON "public"."BottleCountReading"("organizationId" ASC, "lineId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "BottleCountSession_organizationId_countCode_key" ON "public"."BottleCountSession"("organizationId" ASC, "countCode" ASC);

-- CreateIndex
CREATE INDEX "BottleCountSession_organizationId_locationId_idx" ON "public"."BottleCountSession"("organizationId" ASC, "locationId" ASC);

-- CreateIndex
CREATE INDEX "BottleCountSession_organizationId_status_idx" ON "public"."BottleCountSession"("organizationId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "BottleMeasurement_organizationId_locationId_idx" ON "public"."BottleMeasurement"("organizationId" ASC, "locationId" ASC);

-- CreateIndex
CREATE INDEX "BottleMeasurement_organizationId_productId_idx" ON "public"."BottleMeasurement"("organizationId" ASC, "productId" ASC);

-- CreateIndex
CREATE INDEX "BottleMeasurement_sessionId_idx" ON "public"."BottleMeasurement"("sessionId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "CostCenter_organizationId_code_key" ON "public"."CostCenter"("organizationId" ASC, "code" ASC);

-- CreateIndex
CREATE INDEX "CostCenter_organizationId_idx" ON "public"."CostCenter"("organizationId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "CostCenter_organizationId_name_key" ON "public"."CostCenter"("organizationId" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "InventoryException_organizationId_invoiceId_idx" ON "public"."InventoryException"("organizationId" ASC, "invoiceId" ASC);

-- CreateIndex
CREATE INDEX "InventoryException_organizationId_status_idx" ON "public"."InventoryException"("organizationId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "InventoryPostingRule_organizationId_movementType_categoryId_idx" ON "public"."InventoryPostingRule"("organizationId" ASC, "movementType" ASC, "categoryId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "InventoryPostingRule_organizationId_movementType_lineIndex__key" ON "public"."InventoryPostingRule"("organizationId" ASC, "movementType" ASC, "lineIndex" ASC, "productId" ASC, "categoryId" ASC);

-- CreateIndex
CREATE INDEX "InventoryPostingRule_organizationId_movementType_productId_idx" ON "public"."InventoryPostingRule"("organizationId" ASC, "movementType" ASC, "productId" ASC);

-- CreateIndex
CREATE INDEX "InventorySerial_batchId_idx" ON "public"."InventorySerial"("batchId" ASC);

-- CreateIndex
CREATE INDEX "InventorySerial_organizationId_idx" ON "public"."InventorySerial"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "InventorySerial_organizationId_productId_locationId_status_idx" ON "public"."InventorySerial"("organizationId" ASC, "productId" ASC, "locationId" ASC, "status" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "InventorySerial_organizationId_productId_serialNumber_key" ON "public"."InventorySerial"("organizationId" ASC, "productId" ASC, "serialNumber" ASC);

-- CreateIndex
CREATE INDEX "MembershipTier_organizationId_idx" ON "public"."MembershipTier"("organizationId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "MembershipTier_organizationId_name_key" ON "public"."MembershipTier"("organizationId" ASC, "name" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "PaymentTerm_organizationId_code_key" ON "public"."PaymentTerm"("organizationId" ASC, "code" ASC);

-- CreateIndex
CREATE INDEX "PaymentTerm_organizationId_idx" ON "public"."PaymentTerm"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "PosDevice_organizationId_idx" ON "public"."PosDevice"("organizationId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "PosDevice_organizationId_prefix_key" ON "public"."PosDevice"("organizationId" ASC, "prefix" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "PosDevice_organizationId_tokenHash_key" ON "public"."PosDevice"("organizationId" ASC, "tokenHash" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "ProductPackaging_organizationId_barcode_key" ON "public"."ProductPackaging"("organizationId" ASC, "barcode" ASC);

-- CreateIndex
CREATE INDEX "ProductPackaging_organizationId_productId_idx" ON "public"."ProductPackaging"("organizationId" ASC, "productId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "ProductUomConversion_organizationId_productId_fromUomId_toU_key" ON "public"."ProductUomConversion"("organizationId" ASC, "productId" ASC, "fromUomId" ASC, "toUomId" ASC);

-- CreateIndex
CREATE INDEX "ProductUomConversion_organizationId_productId_idx" ON "public"."ProductUomConversion"("organizationId" ASC, "productId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "StockPostingJob_organizationId_invoiceId_key" ON "public"."StockPostingJob"("organizationId" ASC, "invoiceId" ASC);

-- CreateIndex
CREATE INDEX "StockPostingJob_organizationId_status_idx" ON "public"."StockPostingJob"("organizationId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "StockPostingJob_status_nextRetryAt_idx" ON "public"."StockPostingJob"("status" ASC, "nextRetryAt" ASC);

-- CreateIndex
CREATE INDEX "StockReservation_organizationId_productId_variantKey_locati_idx" ON "public"."StockReservation"("organizationId" ASC, "productId" ASC, "variantKey" ASC, "locationId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "StockReservation_organizationId_sourceType_sourceId_idx" ON "public"."StockReservation"("organizationId" ASC, "sourceType" ASC, "sourceId" ASC);

-- CreateIndex
CREATE INDEX "SyncOpDeadLetter_organizationId_deviceId_idx" ON "public"."SyncOpDeadLetter"("organizationId" ASC, "deviceId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "SyncOpDeadLetter_organizationId_opId_key" ON "public"."SyncOpDeadLetter"("organizationId" ASC, "opId" ASC);

-- CreateIndex
CREATE INDEX "SyncOpDeadLetter_organizationId_status_idx" ON "public"."SyncOpDeadLetter"("organizationId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_assignedToId_idx" ON "public"."Task"("organizationId" ASC, "assignedToId" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_branchId_idx" ON "public"."Task"("organizationId" ASC, "branchId" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_category_idx" ON "public"."Task"("organizationId" ASC, "category" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_createdBy_idx" ON "public"."Task"("organizationId" ASC, "createdBy" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_dueDate_idx" ON "public"."Task"("organizationId" ASC, "dueDate" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_idx" ON "public"."Task"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_priority_idx" ON "public"."Task"("organizationId" ASC, "priority" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_shiftId_idx" ON "public"."Task"("organizationId" ASC, "shiftId" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_status_idx" ON "public"."Task"("organizationId" ASC, "status" ASC);

-- CreateIndex
CREATE INDEX "Task_organizationId_taskType_idx" ON "public"."Task"("organizationId" ASC, "taskType" ASC);

-- CreateIndex
CREATE INDEX "TaskActivityLog_organizationId_idx" ON "public"."TaskActivityLog"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "TaskActivityLog_taskId_idx" ON "public"."TaskActivityLog"("taskId" ASC);

-- CreateIndex
CREATE INDEX "TaskAutoRule_organizationId_idx" ON "public"."TaskAutoRule"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "TaskAutoRule_organizationId_triggerEvent_idx" ON "public"."TaskAutoRule"("organizationId" ASC, "triggerEvent" ASC);

-- CreateIndex
CREATE INDEX "TaskChecklistItem_organizationId_idx" ON "public"."TaskChecklistItem"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "TaskChecklistItem_taskId_idx" ON "public"."TaskChecklistItem"("taskId" ASC);

-- CreateIndex
CREATE INDEX "TaskComment_organizationId_idx" ON "public"."TaskComment"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "TaskComment_taskId_idx" ON "public"."TaskComment"("taskId" ASC);

-- CreateIndex
CREATE INDEX "TaskLabel_organizationId_idx" ON "public"."TaskLabel"("organizationId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "TaskLabel_organizationId_name_key" ON "public"."TaskLabel"("organizationId" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "TaskRecurringTemplate_organizationId_idx" ON "public"."TaskRecurringTemplate"("organizationId" ASC);

-- CreateIndex
CREATE INDEX "UomCategory_organizationId_idx" ON "public"."UomCategory"("organizationId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "UomCategory_organizationId_name_key" ON "public"."UomCategory"("organizationId" ASC, "name" ASC);

-- CreateIndex
CREATE INDEX "_TaskLabelLink_B_index" ON "public"."_TaskLabelLink"("B" ASC);

-- CreateIndex
CREATE INDEX "Account_organizationId_categoryId_idx" ON "public"."Account"("organizationId" ASC, "categoryId" ASC);

-- CreateIndex
CREATE INDEX "Account_organizationId_parentAccountId_idx" ON "public"."Account"("organizationId" ASC, "parentAccountId" ASC);

-- CreateIndex
CREATE INDEX "AccountMapping_organizationId_accountId_idx" ON "public"."AccountMapping"("organizationId" ASC, "accountId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "JournalEntry_organizationId_postingKey_key" ON "public"."JournalEntry"("organizationId" ASC, "postingKey" ASC);

-- CreateIndex
CREATE INDEX "JournalEntry_organizationId_postingType_idx" ON "public"."JournalEntry"("organizationId" ASC, "postingType" ASC);

-- CreateIndex
CREATE INDEX "Setting_organizationId_scopeType_scopeId_idx" ON "public"."Setting"("organizationId" ASC, "scopeType" ASC, "scopeId" ASC);

-- CreateIndex
CREATE UNIQUE INDEX "Setting_organizationId_scopeType_scopeId_key_key" ON "public"."Setting"("organizationId" ASC, "scopeType" ASC, "scopeId" ASC, "key" ASC);

-- CreateIndex
CREATE INDEX "UnitOfMeasure_organizationId_categoryId_idx" ON "public"."UnitOfMeasure"("organizationId" ASC, "categoryId" ASC);

-- AddForeignKey
ALTER TABLE "public"."Account" ADD CONSTRAINT "Account_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "public"."AccountCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AccountMapping" ADD CONSTRAINT "AccountMapping_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "public"."Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Asset" ADD CONSTRAINT "Asset_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "public"."AssetCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetAcquisition" ADD CONSTRAINT "AssetAcquisition_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetAssignment" ADD CONSTRAINT "AssetAssignment_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetCategory" ADD CONSTRAINT "AssetCategory_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "public"."AssetCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetCheckInOut" ADD CONSTRAINT "AssetCheckInOut_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetDepreciation" ADD CONSTRAINT "AssetDepreciation_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetDisposal" ADD CONSTRAINT "AssetDisposal_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetDocument" ADD CONSTRAINT "AssetDocument_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetInspection" ADD CONSTRAINT "AssetInspection_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetInsurance" ADD CONSTRAINT "AssetInsurance_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetMaintenance" ADD CONSTRAINT "AssetMaintenance_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetRepair" ADD CONSTRAINT "AssetRepair_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetRevaluation" ADD CONSTRAINT "AssetRevaluation_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetTransfer" ADD CONSTRAINT "AssetTransfer_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."AssetWarranty" ADD CONSTRAINT "AssetWarranty_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "public"."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."BottleCountLine" ADD CONSTRAINT "BottleCountLine_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "public"."BottleCountSession"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."BottleCountReading" ADD CONSTRAINT "BottleCountReading_lineId_fkey" FOREIGN KEY ("lineId") REFERENCES "public"."BottleCountLine"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."InventoryLedger" ADD CONSTRAINT "InventoryLedger_serialId_fkey" FOREIGN KEY ("serialId") REFERENCES "public"."InventorySerial"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."InventorySerial" ADD CONSTRAINT "InventorySerial_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "public"."InventoryBatch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."InventorySerial" ADD CONSTRAINT "InventorySerial_locationId_fkey" FOREIGN KEY ("locationId") REFERENCES "public"."InventoryLocation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."InventorySerial" ADD CONSTRAINT "InventorySerial_productId_fkey" FOREIGN KEY ("productId") REFERENCES "public"."Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."InventorySerial" ADD CONSTRAINT "InventorySerial_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "public"."ProductVariant"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."MenuProduct" ADD CONSTRAINT "MenuProduct_uomId_fkey" FOREIGN KEY ("uomId") REFERENCES "public"."UnitOfMeasure"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Product" ADD CONSTRAINT "Product_productionUomId_fkey" FOREIGN KEY ("productionUomId") REFERENCES "public"."UnitOfMeasure"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Product" ADD CONSTRAINT "Product_recipeUomId_fkey" FOREIGN KEY ("recipeUomId") REFERENCES "public"."UnitOfMeasure"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Product" ADD CONSTRAINT "Product_salesUomId_fkey" FOREIGN KEY ("salesUomId") REFERENCES "public"."UnitOfMeasure"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ProductPackaging" ADD CONSTRAINT "ProductPackaging_productId_fkey" FOREIGN KEY ("productId") REFERENCES "public"."Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ProductUomConversion" ADD CONSTRAINT "ProductUomConversion_fromUomId_fkey" FOREIGN KEY ("fromUomId") REFERENCES "public"."UnitOfMeasure"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ProductUomConversion" ADD CONSTRAINT "ProductUomConversion_productId_fkey" FOREIGN KEY ("productId") REFERENCES "public"."Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."ProductUomConversion" ADD CONSTRAINT "ProductUomConversion_toUomId_fkey" FOREIGN KEY ("toUomId") REFERENCES "public"."UnitOfMeasure"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Task" ADD CONSTRAINT "Task_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Task" ADD CONSTRAINT "Task_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "public"."Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Task" ADD CONSTRAINT "Task_parentTaskId_fkey" FOREIGN KEY ("parentTaskId") REFERENCES "public"."Task"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Task" ADD CONSTRAINT "Task_supervisorId_fkey" FOREIGN KEY ("supervisorId") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."Task" ADD CONSTRAINT "Task_verifiedById_fkey" FOREIGN KEY ("verifiedById") REFERENCES "public"."User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TaskActivityLog" ADD CONSTRAINT "TaskActivityLog_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "public"."Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TaskChecklistItem" ADD CONSTRAINT "TaskChecklistItem_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "public"."Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TaskComment" ADD CONSTRAINT "TaskComment_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "public"."TaskComment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."TaskComment" ADD CONSTRAINT "TaskComment_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "public"."Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."UnitOfMeasure" ADD CONSTRAINT "UnitOfMeasure_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "public"."UomCategory"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."UomCategory" ADD CONSTRAINT "UomCategory_referenceUomId_fkey" FOREIGN KEY ("referenceUomId") REFERENCES "public"."UnitOfMeasure"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."_TaskLabelLink" ADD CONSTRAINT "_TaskLabelLink_A_fkey" FOREIGN KEY ("A") REFERENCES "public"."Task"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."_TaskLabelLink" ADD CONSTRAINT "_TaskLabelLink_B_fkey" FOREIGN KEY ("B") REFERENCES "public"."TaskLabel"("id") ON DELETE CASCADE ON UPDATE CASCADE;
