-- =====================================================================
-- BRIDGE 30 - contract (irreversible without a restore)
-- Generated by: prisma migrate diff --from-url <legacy clone> --to-url ref_baseline_20260727 --script
-- Source draft: reviewed line by line on 2026-09-17; committed as the permanent record.
-- ---------------------------------------------------------------------
-- Runs ONLY after bridge-20-backfill reports 0 unmapped postable accounts and
-- the owner has signed the mapping report. Drops the legacy chart-of-accounts
-- classification columns, whose values are archived in legacy_archive.account.
-- =====================================================================
-- DropIndex
DROP INDEX "public"."Account_organizationId_accountType_idx";

-- AlterTable (contract half of the generated Account statement)
ALTER TABLE "public"."Account" DROP COLUMN "accountType",
DROP COLUMN "isGroup";

-- DropEnum
DROP TYPE "public"."AccountType";
