-- =====================================================================
-- BRIDGE 00 - enum value additions (must COMMIT before the values are used)
-- Generated by: prisma migrate diff --from-url <legacy clone> --to-url ref_baseline_20260727 --script
-- Source draft: reviewed line by line on 2026-09-17; committed as the permanent record.
-- ---------------------------------------------------------------------
-- PostgreSQL refuses to use an enum value added in the same transaction, so
-- these run first, in their own transaction, ahead of bridge-10.
-- =====================================================================
-- AlterEnum
ALTER TYPE "public"."AuditAction" ADD VALUE 'measure';

-- AlterEnum
ALTER TYPE "public"."CostingMethod" ADD VALUE 'SPECIFIC';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.
ALTER TYPE "public"."DiscountSource" ADD VALUE 'customer_discount';

ALTER TYPE "public"."DiscountSource" ADD VALUE 'group_discount';

ALTER TYPE "public"."DiscountSource" ADD VALUE 'membership_discount';

ALTER TYPE "public"."DiscountSource" ADD VALUE 'global_promotion';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.
ALTER TYPE "public"."StockMoveType" ADD VALUE 'internal_use';

ALTER TYPE "public"."StockMoveType" ADD VALUE 'promo_sample';
