/**
 * POS P11 — Offline mode + retry queue.
 *
 * Wraps `useCheckout` so when the network is down, the checkout payload is
 * persisted to IndexedDB with the same Idempotency-Key the backend would
 * have seen. When the network returns, the queue replays each pending sale
 * in order. The backend's existing `IdempotencyInterceptor` ensures a
 * replay never double-charges — it returns the original response.
 *
 * Public surface:
 *   - enqueue(payload)        → stores a sale to retry later
 *   - listPending()            → snapshot of pending sales (for the badge)
 *   - replayAll()             → try to send every pending sale
 *   - useOfflineQueue()        → React hook that watches online/offline + replays
 *
 * The IndexedDB layer is implemented in a tiny helper to avoid pulling
 * in `idb-keyval` as a dep (the wrapper is ~40 lines).
 */

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';

export interface QueuedSale {
  /** Idempotency-Key for the backend. Generated by the cashier UI once
   *  per cart and stored here so a retry uses the SAME key — the backend
   *  returns the original response instead of double-charging. */
  idempotencyKey: string;
  createdAt: number; // epoch ms
  attempts: number;
  lastError?: string;
  /** API path to replay against. Defaults to '/pos/checkout' (counter sale);
   *  a dine-in tab settle queues '/pos/tabs/{tableId}/settle'. */
  endpoint?: string;
  payload: any; // the CheckoutBody / SettleTab body the request normally sends
}

/** A sale the server actively rejected (4xx). Moved out of the pending queue
 *  so it can't poison replay, but kept for cashier/manager review — a rejected
 *  sale is money and must never vanish silently. */
export interface FailedSale extends QueuedSale {
  failedAt: number; // epoch ms
  httpStatus?: number;
}

/* ====================== IndexedDB wrapper ====================== */

const DB_NAME = 'pos-offline-queue';
const DB_VERSION = 2;
const STORE = 'pending-sales';
const FAILED_STORE = 'failed-sales';

let dbPromise: Promise<IDBDatabase> | null = null;

function openDb(): Promise<IDBDatabase> {
  if (dbPromise) return dbPromise;
  dbPromise = new Promise<IDBDatabase>((resolve, reject) => {
    if (typeof indexedDB === 'undefined') {
      reject(new Error('IndexedDB not available'));
      return;
    }
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) {
        db.createObjectStore(STORE, { keyPath: 'idempotencyKey' });
      }
      if (!db.objectStoreNames.contains(FAILED_STORE)) {
        db.createObjectStore(FAILED_STORE, { keyPath: 'idempotencyKey' });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
  return dbPromise;
}

async function idbPut<T>(value: T, store: string = STORE): Promise<void> {
  const db = await openDb();
  return new Promise<void>((resolve, reject) => {
    const tx = db.transaction(store, 'readwrite');
    tx.objectStore(store).put(value);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function idbAll<T>(store: string = STORE): Promise<T[]> {
  const db = await openDb();
  return new Promise<T[]>((resolve, reject) => {
    const tx = db.transaction(store, 'readonly');
    const req = tx.objectStore(store).getAll();
    req.onsuccess = () => resolve(req.result as T[]);
    req.onerror = () => reject(req.error);
  });
}

async function idbDel(key: string, store: string = STORE): Promise<void> {
  const db = await openDb();
  return new Promise<void>((resolve, reject) => {
    const tx = db.transaction(store, 'readwrite');
    tx.objectStore(store).delete(key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function idbClear(store: string = STORE): Promise<void> {
  const db = await openDb();
  return new Promise<void>((resolve, reject) => {
    const tx = db.transaction(store, 'readwrite');
    tx.objectStore(store).clear();
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

/* ====================== Public API ====================== */

export async function enqueueSale(payload: any, opts?: { endpoint?: string; idempotencyKey?: string }): Promise<QueuedSale> {
  // Reuse the cart's key when provided: if an online attempt actually committed
  // but the response was lost, the offline replay sends the SAME key and the
  // backend returns the original result instead of charging twice.
  const idempotencyKey = opts?.idempotencyKey
    ?? ((typeof crypto !== 'undefined' && 'randomUUID' in crypto)
      ? (crypto as any).randomUUID()
      : Math.random().toString(36).slice(2) + Date.now().toString(36));
  const sale: QueuedSale = {
    idempotencyKey,
    createdAt: Date.now(),
    attempts: 0,
    endpoint: opts?.endpoint ?? '/pos/checkout',
    // The key travels ONLY as the Idempotency-Key header. Spreading it into
    // the body trips the API's forbidNonWhitelisted validation → 400 → the
    // sale would be treated as poison and lost.
    // occurredAt pins the sale to the moment it was rung up, so a replay
    // hours/days later still lands on the correct business date.
    payload: { ...payload, occurredAt: new Date().toISOString() },
  };
  await idbPut(sale);
  return sale;
}

export async function listPending(): Promise<QueuedSale[]> {
  try {
    return await idbAll<QueuedSale>();
  } catch {
    return [];
  }
}

export async function clearPending(): Promise<void> {
  try { await idbClear(); } catch { /* noop */ }
}

export async function removePending(idempotencyKey: string): Promise<void> {
  try { await idbDel(idempotencyKey); } catch { /* noop */ }
}

/* ---------------------- Failed-sale review ---------------------- */

export async function listFailed(): Promise<FailedSale[]> {
  try {
    return await idbAll<FailedSale>(FAILED_STORE);
  } catch {
    return [];
  }
}

/** Move a rejected sale back into the pending queue for another attempt
 *  (e.g. after the server-side cause was fixed). Same idempotency key. */
export async function retryFailed(idempotencyKey: string): Promise<void> {
  const failed = await listFailed();
  const sale = failed.find((s) => s.idempotencyKey === idempotencyKey);
  if (!sale) return;
  const { failedAt: _f, httpStatus: _s, ...pending } = sale;
  await idbPut({ ...pending, attempts: 0, lastError: undefined });
  await idbDel(idempotencyKey, FAILED_STORE);
}

/** Permanently discard a rejected sale. Caller must confirm with the user —
 *  this is the only path where a recorded sale is intentionally dropped. */
export async function discardFailed(idempotencyKey: string): Promise<void> {
  try { await idbDel(idempotencyKey, FAILED_STORE); } catch { /* noop */ }
}

/** Replay every pending sale in order. Resolves when the queue is empty
 *  or all retries failed (returns the unresolved list). */
export async function replayAll(onResult?: (sale: QueuedSale, result: 'ok' | 'error') => void): Promise<QueuedSale[]> {
  const pending = await listPending();
  if (pending.length === 0) return [];
  const unresolved: QueuedSale[] = [];
  for (const sale of pending) {
    try {
      await api.post(sale.endpoint ?? '/pos/checkout', sale.payload, {
        headers: { 'Idempotency-Key': sale.idempotencyKey },
      });
      await removePending(sale.idempotencyKey);
      onResult?.(sale, 'ok');
    } catch (e: any) {
      // Mark the attempt + the last error. If we're still offline (no
      // response at all), keep it queued. If the server actively rejected
      // it (4xx), park it in the failed-sales store: it must not poison the
      // queue, but a rejected sale is money and must stay visible for review.
      const status = e?.response?.status;
      const next: QueuedSale = {
        ...sale,
        attempts: sale.attempts + 1,
        lastError: e?.response?.data?.message || e?.message || 'unknown',
      };
      if (status && status >= 400 && status < 500 && status !== 408 && status !== 429) {
        // 4xx other than 408 (timeout) / 429 (rate-limit) — park for review.
        const failed: FailedSale = { ...next, failedAt: Date.now(), httpStatus: status };
        await idbPut(failed, FAILED_STORE);
        await removePending(sale.idempotencyKey);
        onResult?.(sale, 'error');
      } else {
        // Network / 5xx / 408 / 429 — keep queued, update attempt count.
        await idbPut(next);
        unresolved.push(next);
        onResult?.(sale, 'error');
      }
    }
  }
  return unresolved;
}

/* ====================== React hook ====================== */

export interface OfflineQueueState {
  online: boolean;
  pending: QueuedSale[];
  failed: FailedSale[];
  replaying: boolean;
}

/**
 * Drop this hook into the terminal Topbar. It:
 *   1. Tracks navigator.onLine.
 *   2. Polls the pending count every 2s (cheap IndexedDB read).
 *   3. On `online` event, fires replayAll() automatically.
 *
 * Returns the live state for the badge + indicator.
 */
export function useOfflineQueue(): OfflineQueueState & { replay: () => Promise<void>; refresh: () => Promise<void> } {
  const [online, setOnline] = useState<boolean>(typeof navigator !== 'undefined' ? navigator.onLine : true);
  const [pending, setPending] = useState<QueuedSale[]>([]);
  const [failed, setFailed] = useState<FailedSale[]>([]);
  const [replaying, setReplaying] = useState(false);

  // Wire up online/offline listeners.
  useEffect(() => {
    const onOnline = () => setOnline(true);
    const onOffline = () => setOnline(false);
    window.addEventListener('online', onOnline);
    window.addEventListener('offline', onOffline);
    return () => {
      window.removeEventListener('online', onOnline);
      window.removeEventListener('offline', onOffline);
    };
  }, []);

  // Poll the queue.
  useEffect(() => {
    let cancelled = false;
    const refresh = async () => {
      const list = await listPending();
      if (!cancelled) setPending(list);
    };
    refresh();
    const id = setInterval(refresh, 2000);
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  const replay = async () => {
    if (replaying) return;
    setReplaying(true);
    try {
      await replayAll();
      setPending(await listPending());
    } finally {
      setReplaying(false);
    }
  };

  // Auto-replay on online.
  useEffect(() => {
    if (online && pending.length > 0) {
      replay();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [online]);

  return { online, pending, replaying, replay };
}