import { useAuthStore } from '@/stores/auth.store';
import { usePosAuthStore } from './pos-auth.store';
import { useCartStore } from './cart.store';
/**
 * POS P11 — Offline mode + retry queue.
 *
 * Wraps `useCheckout` so when the network is down, the checkout payload is
 * persisted to IndexedDB with the same Idempotency-Key the backend would
 * have seen. When the network returns, the queue replays each pending sale
 * in order. The backend's existing `IdempotencyInterceptor` ensures a
 * replay never double-charges — it returns the original response.
 *
 * Public surface:
 *   - enqueue(payload)        → stores a sale to retry later
 *   - listPending()            → snapshot of pending sales (for the badge)
 *   - replayAll()             → try to send every pending sale
 *   - useOfflineQueue()        → React hook that watches online/offline + replays
 *
 * The IndexedDB layer is implemented in a tiny helper to avoid pulling
 * in `idb-keyval` as a dep (the wrapper is ~40 lines).
 */

import { useEffect, useState, useRef, useCallback } from 'react';
import { api } from '@/lib/api';
import { getApiBaseUrl } from '@/lib/api';

export interface QueuedSale {
  organizationId?: string;
  operatorId?: string;
  terminalId?: string;
  /** Idempotency-Key for the backend. Generated by the cashier UI once
   *  per cart and stored here so a retry uses the SAME key — the backend
   *  returns the original response instead of double-charging. */
  idempotencyKey: string;
  createdAt: number; // epoch ms
  attempts: number;
  lastError?: string;
  /** API path to replay against. Defaults to '/pos/checkout' (counter sale);
   *  a dine-in tab settle queues '/pos/tabs/{tableId}/settle'. */
  endpoint?: string;
  payload: any; // the CheckoutBody / SettleTab body the request normally sends
  /** FIFO ordering token. Replay follows this, not IndexedDB key order —
   *  a cash pay-out recorded after a sale must replay after it, and a drawer
   *  op replayed out of order lands on the wrong session balance. */
  seq?: number;
}

/** A sale the server actively rejected (4xx). Moved out of the pending queue
 *  so it can't poison replay, but kept for cashier/manager review — a rejected
 *  sale is money and must never vanish silently. */
export interface FailedSale extends QueuedSale {
  failedAt: number; // epoch ms
  httpStatus?: number;
  rejection?: any;
}

/* ====================== IndexedDB wrapper ====================== */

const DB_NAME = 'pos-offline-queue';
const DB_VERSION = 3;
const STORE = 'pending-sales';
const FAILED_STORE = 'failed-sales';
const COMPLETED_STORE = 'completed-sales';

let dbPromise: Promise<IDBDatabase> | null = null;

function openDb(): Promise<IDBDatabase> {
  if (dbPromise) return dbPromise;
  dbPromise = new Promise<IDBDatabase>((resolve, reject) => {
    if (typeof indexedDB === 'undefined') {
      reject(new Error('IndexedDB not available'));
      return;
    }
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      const db = req.result;
      if (!db.objectStoreNames.contains(STORE)) {
        db.createObjectStore(STORE, { keyPath: 'idempotencyKey' });
      }
      if (!db.objectStoreNames.contains(FAILED_STORE)) {
        db.createObjectStore(FAILED_STORE, { keyPath: 'idempotencyKey' });
      }
      if (!db.objectStoreNames.contains(COMPLETED_STORE)) db.createObjectStore(COMPLETED_STORE, { keyPath: 'idempotencyKey' });
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
  return dbPromise;
}

async function idbPut<T>(value: T, store: string = STORE): Promise<void> {
  const db = await openDb();
  return new Promise<void>((resolve, reject) => {
    const tx = db.transaction(store, 'readwrite');
    tx.objectStore(store).put(value);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function insertEnvelope(value: QueuedSale): Promise<QueuedSale> {
  const db = await openDb();
  return new Promise((resolve, reject) => {
    const tx = db.transaction(STORE, 'readwrite');
    const store = tx.objectStore(STORE);
    const request = store.get(value.idempotencyKey);
    let saved = value;
    request.onsuccess = () => { if (request.result) saved = request.result; else store.add(value); };
    tx.oncomplete = () => resolve(saved);
    tx.onerror = () => reject(tx.error);
    tx.onabort = () => reject(tx.error ?? new Error('Could not preserve payment'));
  });
}

async function idbAll<T>(store: string = STORE): Promise<T[]> {
  const db = await openDb();
  return new Promise<T[]>((resolve, reject) => {
    const tx = db.transaction(store, 'readonly');
    const req = tx.objectStore(store).getAll();
    req.onsuccess = () => resolve(req.result as T[]);
    req.onerror = () => reject(req.error);
  });
}

async function idbDel(key: string, store: string = STORE): Promise<void> {
  const db = await openDb();
  return new Promise<void>((resolve, reject) => {
    const tx = db.transaction(store, 'readwrite');
    tx.objectStore(store).delete(key);
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

async function idbClear(store: string = STORE): Promise<void> {
  const db = await openDb();
  return new Promise<void>((resolve, reject) => {
    const tx = db.transaction(store, 'readwrite');
    tx.objectStore(store).clear();
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
}

/**
 * Check if the local API server is reachable (not internet connectivity).
 * Uses a bare fetch to the /health endpoint with a short timeout to avoid
 * the axios interceptor's "Network error" toast spam + token-refresh flow.
 */
async function checkServerOnline(): Promise<boolean> {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 3000);
    const base = getApiBaseUrl();
    const url = base ? `${base}/health` : '/api/v1/health';
    const res = await fetch(url, {
      method: 'GET',
      signal: controller.signal,
      // Don't send cookies or auth headers - this is a lightweight probe
      credentials: 'omit',
    });
    clearTimeout(timeoutId);
    return res.ok;
  } catch {
    return false;
  }
}

/* ====================== Public API ====================== */

function newKey(): string {
  return (typeof crypto !== 'undefined' && 'randomUUID' in crypto)
    ? (crypto as any).randomUUID()
    : Math.random().toString(36).slice(2) + Date.now().toString(36);
}

/** Monotonic FIFO token. Derived from the queue's current max so it survives
 *  a page reload (an in-memory counter would restart at 0 and reorder). */
async function nextSeq(): Promise<number> {
  const pending = await listPending();
  return pending.reduce((max, s) => Math.max(max, s.seq ?? 0), 0) + 1;
}

export function operationIdentity() {
  const organizationId = useAuthStore.getState().organization?.id;
  const operatorId = usePosAuthStore.getState().user?.userId ?? useAuthStore.getState().user?.id;
  if (!organizationId || !operatorId) throw new Error('Sign in before recording a payment');
  let terminalId = localStorage.getItem('pos-terminal-id');
  if (!terminalId) { terminalId = crypto.randomUUID(); localStorage.setItem('pos-terminal-id', terminalId); }
  return { organizationId, operatorId, terminalId };
}

export async function enqueueSale(payload: any, opts?: { endpoint?: string; idempotencyKey?: string }): Promise<QueuedSale> {
  const idempotencyKey = opts?.idempotencyKey ?? newKey();
  const identity = operationIdentity();
  const existing = (await idbAll<QueuedSale>()).find((sale) => sale.idempotencyKey === idempotencyKey);
  if (existing) {
    if (existing.organizationId !== identity.organizationId || existing.operatorId !== identity.operatorId) throw new Error('This pending sale belongs to another operator or organization');
    return existing; // immutable: a fallback can never replace an earlier body
  }
  const sale: QueuedSale = { ...identity, idempotencyKey, createdAt: Date.now(), attempts: 0, endpoint: opts?.endpoint ?? '/pos/checkout', seq: await nextSeq(), payload: JSON.parse(JSON.stringify(payload)) };
  return insertEnvelope(sale);
}

/** Write-ahead operation envelope: persist before the FIRST network attempt. */
export async function submitSaleOperation(endpoint: string, input: any, key: string) {
  const completed = (await idbAll<QueuedSale & { response: any }>(COMPLETED_STORE)).find((s) => s.idempotencyKey === key);
  const identity = operationIdentity();
  if (completed) {
    if (completed.organizationId !== identity.organizationId || completed.operatorId !== identity.operatorId || completed.endpoint !== endpoint) throw new Error('The completed operation belongs to another operator or endpoint');
    if (useCartStore.getState().idempotencyKey === key) useCartStore.setState({ operationPending: false });
    return completed.response;
  }
  const prior = (await idbAll<QueuedSale>()).find((s) => s.idempotencyKey === key);
  const isSale = /\/checkout$|\/settle$/.test(endpoint);
  const payload = JSON.parse(JSON.stringify({ ...input, ...(isSale ? { occurredAt: prior?.payload?.occurredAt ?? input.occurredAt ?? new Date().toISOString() } : {}) }));
  if (prior?.payload.approvalToken) { payload.approvalToken = prior.payload.approvalToken; delete payload.overridePin; }
  if (!prior && payload.overrideById && payload.overridePin) {
    // The grant is bound to WHAT it authorises; the server rejects it on any
    // other kind of operation, so a refund approval can never settle a discount.
    const overrideKind = /\/refund$/.test(endpoint) ? 'manual_refund' : /\/write-off$/.test(endpoint) ? 'write_off' : 'discount';
    const approved = await api.post('/pos/operation-approval', { managerId: payload.overrideById, pin: payload.overridePin, operationKey: key, endpoint, payload, overrideKind });
    payload.approvalToken = approved.data.approvalToken;
    delete payload.overridePin;
  }
  if (prior && (prior.endpoint !== endpoint || JSON.stringify(prior.payload) !== JSON.stringify(payload))) throw new Error('This sale has a pending payment. Resolve its original attempt before changing the payment or cart.');
  const sale = await enqueueSale(payload, { endpoint, idempotencyKey: key });
  if (sale.organizationId !== identity.organizationId || sale.operatorId !== identity.operatorId || sale.endpoint !== endpoint || JSON.stringify(sale.payload) !== JSON.stringify(payload)) throw new Error('A concurrent payment already preserved a different request. Recover the original operation.');
  if (useCartStore.getState().idempotencyKey === key) useCartStore.setState({ operationPending: true });
  try {
    const result = await api.post(endpoint, sale.payload, { headers: { 'Idempotency-Key': key } });
    await idbPut({ ...sale, response: result.data }, COMPLETED_STORE);
    await removePending(key);
    if (useCartStore.getState().idempotencyKey === key) useCartStore.setState({ operationPending: false });
    return result.data;
  } catch (error: any) {
    if (error?.response?.data?.safeToRetry) {
      await idbPut({ ...sale, failedAt: Date.now(), httpStatus: error.response.status, rejection: error.response.data }, FAILED_STORE);
      await removePending(key);
      if (useCartStore.getState().idempotencyKey === key) useCartStore.setState({ idempotencyKey: newKey(), operationPending: false });
    }
    throw error;
  }
}

function entityOperationSlot(endpoint: string) {
  const identity = operationIdentity();
  return `pos-entity-operation:${identity.organizationId}:${identity.operatorId}:${endpoint}`;
}
export function pendingEntityOperationKey(endpoint: string) { return localStorage.getItem(entityOperationSlot(endpoint)); }
export async function submitEntitySaleOperation(endpoint: string, body: any) {
  const slot = entityOperationSlot(endpoint), key = localStorage.getItem(slot) ?? newKey();
  localStorage.setItem(slot, key);
  try { const result = await submitSaleOperation(endpoint, body, key); localStorage.removeItem(slot); return result; }
  catch (e: any) { if (e?.response?.data?.safeToRetry) localStorage.removeItem(slot); throw e; }
}
export async function recoverEntitySaleOperation(endpoint: string) {
  const slot = entityOperationSlot(endpoint), key = localStorage.getItem(slot);
  if (!key) throw new Error('No pending operation for this invoice');
  try { const result = await recoverSaleOperation(key); localStorage.removeItem(slot); return result; }
  catch (e: any) { if (e?.response?.data?.safeToRetry) localStorage.removeItem(slot); throw e; }
}

export async function recoverSaleOperation(key: string) {
  const sale = [...await idbAll<QueuedSale>(), ...await idbAll<QueuedSale>(COMPLETED_STORE), ...await idbAll<FailedSale>(FAILED_STORE)].find((s) => s.idempotencyKey === key);
  if (!sale) throw new Error('The original operation is missing. Ask a manager to review the payment before starting another sale.');
  const identity = operationIdentity();
  if (sale.organizationId !== identity.organizationId || sale.operatorId !== identity.operatorId) throw new Error('Recover this operation as its original operator');
  const rejection = (sale as FailedSale).rejection;
  if (rejection?.safeToRetry) {
    if (useCartStore.getState().idempotencyKey === key) useCartStore.setState({ idempotencyKey: newKey(), operationPending: false });
    throw Object.assign(new Error(rejection.message || 'Payment was rejected before any sale committed. Your cart is preserved; correct the payment and try again.'), { response: { data: rejection } });
  }
  return submitSaleOperation(sale.endpoint ?? '/pos/checkout', sale.payload, key);
}

/**
 * Queue a cash-drawer movement (pay-in / pay-out / adjustment) made while the
 * server was unreachable. Ordering matters: these replay after the sales that
 * preceded them, so the session's expected-cash maths reconstructs correctly.
 */
export async function enqueueCashMovement(_payload: {
  sessionId?: string;
  movementType: 'pay_in' | 'pay_out' | 'adjustment';
  amount: number;
  reason?: string;
  approvedById?: string;
  approverEmail?: string;
  managerPin?: string;
}): Promise<QueuedSale> {
  throw new Error('Cash movements require an online connection and verified approval. No manager credential is saved offline.');
}

/**
 * Queue a kitchen round for a table's tab.
 *
 * Uses `/pos/tabs/{tableId}/items` (append) rather than `/save` (full replace):
 * a replace replayed later would clobber whatever another terminal has since
 * added to that tab, and would 409 on the optimistic-lock version. Appending
 * is the only replay-safe shape.
 */
export async function enqueueTabRound(tableId: string, payload: {
  lines: any[];
  guestCount?: number;
  partnerId?: string;
  sendToKitchen?: boolean;
  overrideById?: string;
}): Promise<QueuedSale> {
  return enqueueSale(payload, { endpoint: `/pos/tabs/${tableId}/items` });
}

export async function listPending(): Promise<QueuedSale[]> {
  try {
    return await idbAll<QueuedSale>();
  } catch {
    return [];
  }
}

export async function clearPending(): Promise<void> {
  try { await idbClear(); } catch { /* noop */ }
}

export async function removePending(idempotencyKey: string): Promise<void> {
  try { await idbDel(idempotencyKey); } catch { /* noop */ }
}

/* ---------------------- Failed-sale review ---------------------- */

export async function listFailed(): Promise<FailedSale[]> {
  try {
    return await idbAll<FailedSale>(FAILED_STORE);
  } catch {
    return [];
  }
}

/** Move a rejected sale back into the pending queue for another attempt
 *  (e.g. after the server-side cause was fixed). Same idempotency key. */
export async function retryFailed(idempotencyKey: string): Promise<void> {
  const failed = await listFailed();
  const sale = failed.find((s) => s.idempotencyKey === idempotencyKey);
  if (!sale) return;
  const { failedAt: _f, httpStatus: _s, ...pending } = sale;
  await idbPut({ ...pending, attempts: 0, lastError: undefined });
  await idbDel(idempotencyKey, FAILED_STORE);
}

/** Permanently discard a rejected sale. Caller must confirm with the user —
 *  this is the only path where a recorded sale is intentionally dropped. */
export async function discardFailed(idempotencyKey: string): Promise<void> {
  try { await idbDel(idempotencyKey, FAILED_STORE); } catch { /* noop */ }
}

/** Replay every pending sale in order. Resolves when the queue is empty
 *  or all retries failed (returns the unresolved list). */
export async function replayAll(onResult?: (sale: QueuedSale, result: 'ok' | 'error') => void): Promise<QueuedSale[]> {
  const pending = await listPending();
  if (pending.length === 0) return [];
  // IndexedDB getAll() returns rows in KEY order (random uuids) — replay must
  // follow the order things actually happened. Older rows predate `seq`; fall
  // back to createdAt for those.
  pending.sort((a, b) => (a.seq ?? 0) - (b.seq ?? 0) || a.createdAt - b.createdAt);
  const unresolved: QueuedSale[] = [];
  for (const sale of pending) {
    try {
      const identity = operationIdentity();
      if (sale.organizationId !== identity.organizationId || sale.operatorId !== identity.operatorId || sale.terminalId !== identity.terminalId) {
        unresolved.push({ ...sale, lastError: 'Sign in as the original operator to recover this operation' });
        continue;
      }
      const result = await api.post(sale.endpoint ?? '/pos/checkout', sale.payload, {
        headers: { 'Idempotency-Key': sale.idempotencyKey },
      });
      await idbPut({ ...sale, response: result.data }, COMPLETED_STORE);
      await removePending(sale.idempotencyKey);
      onResult?.(sale, 'ok');
    } catch (e: any) {
      // Mark the attempt + the last error. If we're still offline (no
      // response at all), keep it queued. If the server actively rejected
      // it (4xx), park it in the failed-sales store: it must not poison the
      // queue, but a rejected sale is money and must stay visible for review.
      const status = e?.response?.status;
      const next: QueuedSale = {
        ...sale,
        attempts: sale.attempts + 1,
        lastError: e?.response?.data?.message || e?.message || 'unknown',
      };
      if (status && status >= 400 && status < 500 && status !== 401 && status !== 403 && status !== 409 && status !== 408 && status !== 429) {
        // 4xx other than 408 (timeout) / 429 (rate-limit) — park for review.
        const failed: FailedSale = { ...next, failedAt: Date.now(), httpStatus: status, rejection: e?.response?.data };
        await idbPut(failed, FAILED_STORE);
        await removePending(sale.idempotencyKey);
        onResult?.(sale, 'error');
      } else {
        // Network / 5xx / 408 / 429 — keep queued, update attempt count.
        await idbPut(next);
        unresolved.push(next);
        onResult?.(sale, 'error');
      }
    }
  }
  return unresolved;
}

/* ====================== React hook ====================== */

export interface OfflineQueueState {
  online: boolean;
  pending: QueuedSale[];
  failed: FailedSale[];
  replaying: boolean;
}

/**
 * Drop this hook into the terminal Topbar. It:
 *   1. Tracks server reachability via health polling (10s interval), NOT navigator.onLine.
 *   2. Polls the pending count every 2s (cheap IndexedDB read).
 *   3. window.online/offline events are kept as fast-path hints that trigger an immediate health re-check.
 *   4. Auto-replay on a 15s timer whenever online && pending.length > 0 (previously replay fired only on
 *      the browser online event — which never fires without internet, so queued sales were stuck in IndexedDB forever).
 *
 * Returns the live state for the badge + indicator.
 */
export function useOfflineQueue(): Omit<OfflineQueueState, 'failed'> & { replay: () => Promise<void> } {
  const [online, setOnline] = useState<boolean>(true); // start optimistic; health check will correct
  const [pending, setPending] = useState<QueuedSale[]>([]);
  const [replaying, setReplaying] = useState(false);
  const healthCheckRef = useRef<number | null>(null);
  const replayTimerRef = useRef<number | null>(null);
  const replayRef = useRef<() => Promise<void>>();

  // Health check function
  const checkHealth = useCallback(async () => {
    const reachable = await checkServerOnline();
    setOnline(reachable);
    return reachable;
  }, []);

  // Replay function - defined early so it can be used in useEffects
  const replay = useCallback(async () => {
    if (replaying) return;
    setReplaying(true);
    try {
      await replayAll();
      setPending(await listPending());
    } finally {
      setReplaying(false);
    }
  }, [replaying]);

  // Store replay in ref for use in other useEffects
  useEffect(() => {
    replayRef.current = replay;
  }, [replay]);

  // Wire up online/offline listeners as fast-path hints only
  useEffect(() => {
    const onOnline = () => checkHealth();
    const onOffline = () => checkHealth();
    window.addEventListener('online', onOnline);
    window.addEventListener('offline', onOffline);
    return () => {
      window.removeEventListener('online', onOnline);
      window.removeEventListener('offline', onOffline);
    };
  }, [checkHealth]);

  // Poll server health every 10s
  useEffect(() => {
    let cancelled = false;
    const check = async () => {
      const reachable = await checkHealth();
      if (!cancelled && reachable && pending.length > 0) {
        replayRef.current?.();
      }
    };
    check(); // immediate check on mount
    healthCheckRef.current = window.setInterval(check, 10_000);
    return () => {
      cancelled = true;
      if (healthCheckRef.current) clearInterval(healthCheckRef.current);
    };
  }, [checkHealth, pending.length]);

  // Poll the queue.
  useEffect(() => {
    let cancelled = false;
    const refresh = async () => {
      const list = await listPending();
      if (!cancelled) setPending(list);
    };
    refresh();
    const id = setInterval(refresh, 2000);
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  // Auto-replay timer: every 15s when online and pending > 0
  useEffect(() => {
    if (online && pending.length > 0) {
      replayTimerRef.current = window.setInterval(() => {
        if (online) replayRef.current?.(); // online captured in closure; re-check inside replay()
      }, 15_000);
    }
    return () => {
      if (replayTimerRef.current) clearInterval(replayTimerRef.current);
    };
  }, [online, pending.length]);

  return { online, pending, replaying, replay };
}

/**
 * Companion hook for the failed-sales review UI. Kept separate from
 * useOfflineQueue so the topbar badge stays cheap; only the review
 * dialog (and the badge count) needs this.
 */
export function useFailedSales(): {
  failed: FailedSale[];
  retry: (idempotencyKey: string) => Promise<void>;
  discard: (idempotencyKey: string) => Promise<void>;
  refresh: () => Promise<void>;
} {
  const [failed, setFailed] = useState<FailedSale[]>([]);

  const refresh = async () => setFailed(await listFailed());

  useEffect(() => {
    let cancelled = false;
    const tick = async () => {
      const list = await listFailed();
      if (!cancelled) setFailed(list);
    };
    tick();
    const id = setInterval(tick, 5000);
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  const retry = async (key: string) => {
    await retryFailed(key);
    await refresh();
  };
  const discard = async (key: string) => {
    await discardFailed(key);
    await refresh();
  };

  return { failed, retry, discard, refresh };
}
